server:
 port: 8080
eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka/
spring:
 application:
  name: APIGateWayService
  data:
      mongodb:
        uri: mongodb+srv://lrbangare97:lalesh@cluster0.dnar8.mongodb.net/AgricultureDatabase?retryWrites=true&w=majority
  main:
     allow-circular-references: true
     allow-bean-definition-overriding: true
     mvc:
      pathmatch:
        matching-strategy: ant-path-matcher 
 cloud:
  gateway:
   routes:
     - id: AgricultureCropSystemfarmer
       uri: http://localhost:8082/
       predicates:
       - Path=/api/v1/**
     - id: DealerModule
       uri: http://localhost:8083/
       predicates:
       - Path=/api/v2/**
  
       