server:
  port: 8082
spring:
  application:
      name: AgricultureCropSystemfarmer
  data:
   mongodb:
    uri: mongodb+srv://lrbangare97:lalesh@cluster0.dnar8.mongodb.net/AgricultureDatabase?retryWrites=true&w=majority
  main:
      allow-circular-references: true
      allow-bean-definition-overriding: true    
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

eureka:
   client:
      service-url:
       defaultZone: http://localhost:8761/eureka/
logging:
  file:
   path: FarmerLogs/farmlog.log  
   name: log.txt   
farmerModel:
         exception: 
               farmerModelExists: Farmer id already exists!
               farmerModelNotFound: Farmer id not found...
jwt:
 secret: secrectkey123
           

#logging.level.root=INFO
#logging.level.com.cg=TRACE
